#!/usr/bin/env python3
"""
app.yaml -> values.yaml for charts/sandbox-app.

This is the ONLY thing the 'agent' in Daniel's proposal needs to do at deploy
time, and it is deterministic. The output is a ten-line diff a reviewer reads
in the PR. Platform defaults come from the chart's values.yaml, never from here.
"""
from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
ALLOWLIST = ROOT / "allowlist.yaml"


def render(manifest: dict, allow: dict, acr: str, tag: str) -> dict:
    stack = manifest["stack"]
    stack_cfg = allow["stacks"][stack]
    port = manifest.get("port", stack_cfg.get("port", 8080))
    ttl = manifest.get("ttlDays", 30)
    expires = (dt.datetime.now(dt.timezone.utc) + dt.timedelta(days=ttl)).replace(microsecond=0)

    return {
        "app": {
            "name": manifest["name"],
            "stack": stack,
            "port": port,
            "entrypoint": manifest.get("entrypoint", ""),
            "owner": {
                "email": manifest["owner"]["email"],
                "businessUnit": manifest["owner"]["businessUnit"],
                "sponsor": manifest["owner"].get("sponsor", ""),
            },
            "dataClassification": manifest["dataClassification"],
            "ttlDays": ttl,
        },
        "image": {
            "repository": f"{acr}/sandbox/{manifest['name']}",
            "tag": tag,
        },
        "egress": {
            "fqdns": (manifest.get("needs") or {}).get("egress") or [],
            # CIDRs are resolved by the pipeline step after human approval.
            "cidrs": [],
        },
        "database": {"enabled": bool((manifest.get("needs") or {}).get("database", False))},
        "expiresAt": expires.isoformat().replace("+00:00", "Z"),
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("app_dir", type=Path)
    ap.add_argument("--acr", default="<your-acr>.azurecr.io")
    ap.add_argument("--tag", default="git-sha")
    ap.add_argument("--allowlist", type=Path, default=ALLOWLIST)
    ap.add_argument("-o", "--out", type=Path)
    args = ap.parse_args()

    manifest = yaml.safe_load((args.app_dir / "app.yaml").read_text())
    allow = yaml.safe_load(args.allowlist.read_text())
    values = render(manifest, allow, args.acr, args.tag)
    text = "# Generated by tools/render_values.py from app.yaml. Review the diff; do not hand-edit.\n" + yaml.safe_dump(values, sort_keys=False)
    if args.out:
        args.out.write_text(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
